apiVersion: 1

datasources:
  - name: DMS Loki
    uid: dms-loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: '"trace_id":"([a-f0-9]{32})"'
          datasourceUid: dms-tempo
          url: '$${__value.raw}'
