// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: dms/v1/client_node.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerService_OpenSession_FullMethodName     = "/dms.v1.WorkerService/OpenSession"
	WorkerService_Session_FullMethodName         = "/dms.v1.WorkerService/Session"
	WorkerService_Heartbeat_FullMethodName       = "/dms.v1.WorkerService/Heartbeat"
	WorkerService_AllocateStaging_FullMethodName = "/dms.v1.WorkerService/AllocateStaging"
	WorkerService_AcquireRegion_FullMethodName   = "/dms.v1.WorkerService/AcquireRegion"
	WorkerService_DeleteStaging_FullMethodName   = "/dms.v1.WorkerService/DeleteStaging"
	WorkerService_SetInline_FullMethodName       = "/dms.v1.WorkerService/SetInline"
	WorkerService_Set_FullMethodName             = "/dms.v1.WorkerService/Set"
	WorkerService_Delete_FullMethodName          = "/dms.v1.WorkerService/Delete"
	WorkerService_Get_FullMethodName             = "/dms.v1.WorkerService/Get"
	WorkerService_Stat_FullMethodName            = "/dms.v1.WorkerService/Stat"
	WorkerService_Scan_FullMethodName            = "/dms.v1.WorkerService/Scan"
	WorkerService_MSet_FullMethodName            = "/dms.v1.WorkerService/MSet"
	WorkerService_MGet_FullMethodName            = "/dms.v1.WorkerService/MGet"
	WorkerService_SetRange_FullMethodName        = "/dms.v1.WorkerService/SetRange"
	WorkerService_HSet_FullMethodName            = "/dms.v1.WorkerService/HSet"
	WorkerService_HGet_FullMethodName            = "/dms.v1.WorkerService/HGet"
	WorkerService_HMGet_FullMethodName           = "/dms.v1.WorkerService/HMGet"
	WorkerService_HGetAll_FullMethodName         = "/dms.v1.WorkerService/HGetAll"
	WorkerService_HDelete_FullMethodName         = "/dms.v1.WorkerService/HDelete"
	WorkerService_HScan_FullMethodName           = "/dms.v1.WorkerService/HScan"
	WorkerService_HWriteAt_FullMethodName        = "/dms.v1.WorkerService/HWriteAt"
)

// WorkerServiceClient is the client API for WorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Client -> Node 业务合同。普通请求使用 unary；Session 是客户端发起的双向长流，
// 用于会话消息与缓存失效通知，不需要 Node 反向连接 Client。
// 大 payload 通过独立传输能力或本地共享内存交付，业务语义与具体传输路径分离。
type WorkerServiceClient interface {
	OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*OpenSessionResponse, error)
	// One long-lived stream per Client session. The Client opens the stream, so
	// the Node can push events without reverse-dialling the Client process.
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientSessionMessage, NodeSessionEvent], error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	AllocateStaging(ctx context.Context, in *AllocateStagingRequest, opts ...grpc.CallOption) (*AllocateStagingResponse, error)
	// Authorizes one Client session to map a Region that appeared in a SHM
	// slice. The response carries only a one-shot capability; the memfd itself
	// is delivered out-of-band by the local SCM_RIGHTS broker.
	AcquireRegion(ctx context.Context, in *AcquireRegionRequest, opts ...grpc.CallOption) (*AcquireRegionResponse, error)
	DeleteStaging(ctx context.Context, in *DeleteStagingRequest, opts ...grpc.CallOption) (*DeleteStagingResponse, error)
	// Small values use one control RPC. Node still executes the same internal
	// stage -> seal -> commit state machine, but no transfer ticket is exposed.
	SetInline(ctx context.Context, in *SetInlineRequest, opts ...grpc.CallOption) (*SetResponse, error)
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error)
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error)
	MSet(ctx context.Context, in *MSetRequest, opts ...grpc.CallOption) (*MSetResponse, error)
	MGet(ctx context.Context, in *MGetRequest, opts ...grpc.CallOption) (*MGetResponse, error)
	SetRange(ctx context.Context, in *SetRangeRequest, opts ...grpc.CallOption) (*SetResponse, error)
	HSet(ctx context.Context, in *HSetRequest, opts ...grpc.CallOption) (*HSetResponse, error)
	HGet(ctx context.Context, in *HGetRequest, opts ...grpc.CallOption) (*HGetResponse, error)
	HMGet(ctx context.Context, in *HMGetRequest, opts ...grpc.CallOption) (*HMGetResponse, error)
	HGetAll(ctx context.Context, in *HGetAllRequest, opts ...grpc.CallOption) (*HGetAllResponse, error)
	HDelete(ctx context.Context, in *HDeleteRequest, opts ...grpc.CallOption) (*HSetResponse, error)
	HScan(ctx context.Context, in *HScanRequest, opts ...grpc.CallOption) (*HScanResponse, error)
	HWriteAt(ctx context.Context, in *HWriteAtRequest, opts ...grpc.CallOption) (*HWriteAtResponse, error)
}

type workerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerServiceClient(cc grpc.ClientConnInterface) WorkerServiceClient {
	return &workerServiceClient{cc}
}

func (c *workerServiceClient) OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*OpenSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenSessionResponse)
	err := c.cc.Invoke(ctx, WorkerService_OpenSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientSessionMessage, NodeSessionEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[0], WorkerService_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientSessionMessage, NodeSessionEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_SessionClient = grpc.BidiStreamingClient[ClientSessionMessage, NodeSessionEvent]

func (c *workerServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, WorkerService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) AllocateStaging(ctx context.Context, in *AllocateStagingRequest, opts ...grpc.CallOption) (*AllocateStagingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocateStagingResponse)
	err := c.cc.Invoke(ctx, WorkerService_AllocateStaging_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) AcquireRegion(ctx context.Context, in *AcquireRegionRequest, opts ...grpc.CallOption) (*AcquireRegionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcquireRegionResponse)
	err := c.cc.Invoke(ctx, WorkerService_AcquireRegion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) DeleteStaging(ctx context.Context, in *DeleteStagingRequest, opts ...grpc.CallOption) (*DeleteStagingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteStagingResponse)
	err := c.cc.Invoke(ctx, WorkerService_DeleteStaging_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) SetInline(ctx context.Context, in *SetInlineRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, WorkerService_SetInline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, WorkerService_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, WorkerService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, WorkerService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatResponse)
	err := c.cc.Invoke(ctx, WorkerService_Stat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, WorkerService_Scan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) MSet(ctx context.Context, in *MSetRequest, opts ...grpc.CallOption) (*MSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MSetResponse)
	err := c.cc.Invoke(ctx, WorkerService_MSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) MGet(ctx context.Context, in *MGetRequest, opts ...grpc.CallOption) (*MGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MGetResponse)
	err := c.cc.Invoke(ctx, WorkerService_MGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) SetRange(ctx context.Context, in *SetRangeRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, WorkerService_SetRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) HSet(ctx context.Context, in *HSetRequest, opts ...grpc.CallOption) (*HSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HSetResponse)
	err := c.cc.Invoke(ctx, WorkerService_HSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) HGet(ctx context.Context, in *HGetRequest, opts ...grpc.CallOption) (*HGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HGetResponse)
	err := c.cc.Invoke(ctx, WorkerService_HGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) HMGet(ctx context.Context, in *HMGetRequest, opts ...grpc.CallOption) (*HMGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HMGetResponse)
	err := c.cc.Invoke(ctx, WorkerService_HMGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) HGetAll(ctx context.Context, in *HGetAllRequest, opts ...grpc.CallOption) (*HGetAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HGetAllResponse)
	err := c.cc.Invoke(ctx, WorkerService_HGetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) HDelete(ctx context.Context, in *HDeleteRequest, opts ...grpc.CallOption) (*HSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HSetResponse)
	err := c.cc.Invoke(ctx, WorkerService_HDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) HScan(ctx context.Context, in *HScanRequest, opts ...grpc.CallOption) (*HScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HScanResponse)
	err := c.cc.Invoke(ctx, WorkerService_HScan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) HWriteAt(ctx context.Context, in *HWriteAtRequest, opts ...grpc.CallOption) (*HWriteAtResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HWriteAtResponse)
	err := c.cc.Invoke(ctx, WorkerService_HWriteAt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServiceServer is the server API for WorkerService service.
// All implementations must embed UnimplementedWorkerServiceServer
// for forward compatibility.
//
// Client -> Node 业务合同。普通请求使用 unary；Session 是客户端发起的双向长流，
// 用于会话消息与缓存失效通知，不需要 Node 反向连接 Client。
// 大 payload 通过独立传输能力或本地共享内存交付，业务语义与具体传输路径分离。
type WorkerServiceServer interface {
	OpenSession(context.Context, *OpenSessionRequest) (*OpenSessionResponse, error)
	// One long-lived stream per Client session. The Client opens the stream, so
	// the Node can push events without reverse-dialling the Client process.
	Session(grpc.BidiStreamingServer[ClientSessionMessage, NodeSessionEvent]) error
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	AllocateStaging(context.Context, *AllocateStagingRequest) (*AllocateStagingResponse, error)
	// Authorizes one Client session to map a Region that appeared in a SHM
	// slice. The response carries only a one-shot capability; the memfd itself
	// is delivered out-of-band by the local SCM_RIGHTS broker.
	AcquireRegion(context.Context, *AcquireRegionRequest) (*AcquireRegionResponse, error)
	DeleteStaging(context.Context, *DeleteStagingRequest) (*DeleteStagingResponse, error)
	// Small values use one control RPC. Node still executes the same internal
	// stage -> seal -> commit state machine, but no transfer ticket is exposed.
	SetInline(context.Context, *SetInlineRequest) (*SetResponse, error)
	Set(context.Context, *SetRequest) (*SetResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Stat(context.Context, *StatRequest) (*StatResponse, error)
	Scan(context.Context, *ScanRequest) (*ScanResponse, error)
	MSet(context.Context, *MSetRequest) (*MSetResponse, error)
	MGet(context.Context, *MGetRequest) (*MGetResponse, error)
	SetRange(context.Context, *SetRangeRequest) (*SetResponse, error)
	HSet(context.Context, *HSetRequest) (*HSetResponse, error)
	HGet(context.Context, *HGetRequest) (*HGetResponse, error)
	HMGet(context.Context, *HMGetRequest) (*HMGetResponse, error)
	HGetAll(context.Context, *HGetAllRequest) (*HGetAllResponse, error)
	HDelete(context.Context, *HDeleteRequest) (*HSetResponse, error)
	HScan(context.Context, *HScanRequest) (*HScanResponse, error)
	HWriteAt(context.Context, *HWriteAtRequest) (*HWriteAtResponse, error)
	mustEmbedUnimplementedWorkerServiceServer()
}

// UnimplementedWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServiceServer struct{}

func (UnimplementedWorkerServiceServer) OpenSession(context.Context, *OpenSessionRequest) (*OpenSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenSession not implemented")
}
func (UnimplementedWorkerServiceServer) Session(grpc.BidiStreamingServer[ClientSessionMessage, NodeSessionEvent]) error {
	return status.Errorf(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedWorkerServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedWorkerServiceServer) AllocateStaging(context.Context, *AllocateStagingRequest) (*AllocateStagingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocateStaging not implemented")
}
func (UnimplementedWorkerServiceServer) AcquireRegion(context.Context, *AcquireRegionRequest) (*AcquireRegionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcquireRegion not implemented")
}
func (UnimplementedWorkerServiceServer) DeleteStaging(context.Context, *DeleteStagingRequest) (*DeleteStagingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStaging not implemented")
}
func (UnimplementedWorkerServiceServer) SetInline(context.Context, *SetInlineRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetInline not implemented")
}
func (UnimplementedWorkerServiceServer) Set(context.Context, *SetRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedWorkerServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedWorkerServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedWorkerServiceServer) Stat(context.Context, *StatRequest) (*StatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedWorkerServiceServer) Scan(context.Context, *ScanRequest) (*ScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedWorkerServiceServer) MSet(context.Context, *MSetRequest) (*MSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MSet not implemented")
}
func (UnimplementedWorkerServiceServer) MGet(context.Context, *MGetRequest) (*MGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MGet not implemented")
}
func (UnimplementedWorkerServiceServer) SetRange(context.Context, *SetRangeRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRange not implemented")
}
func (UnimplementedWorkerServiceServer) HSet(context.Context, *HSetRequest) (*HSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HSet not implemented")
}
func (UnimplementedWorkerServiceServer) HGet(context.Context, *HGetRequest) (*HGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HGet not implemented")
}
func (UnimplementedWorkerServiceServer) HMGet(context.Context, *HMGetRequest) (*HMGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HMGet not implemented")
}
func (UnimplementedWorkerServiceServer) HGetAll(context.Context, *HGetAllRequest) (*HGetAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HGetAll not implemented")
}
func (UnimplementedWorkerServiceServer) HDelete(context.Context, *HDeleteRequest) (*HSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HDelete not implemented")
}
func (UnimplementedWorkerServiceServer) HScan(context.Context, *HScanRequest) (*HScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HScan not implemented")
}
func (UnimplementedWorkerServiceServer) HWriteAt(context.Context, *HWriteAtRequest) (*HWriteAtResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HWriteAt not implemented")
}
func (UnimplementedWorkerServiceServer) mustEmbedUnimplementedWorkerServiceServer() {}
func (UnimplementedWorkerServiceServer) testEmbeddedByValue()                       {}

// UnsafeWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServiceServer will
// result in compilation errors.
type UnsafeWorkerServiceServer interface {
	mustEmbedUnimplementedWorkerServiceServer()
}

func RegisterWorkerServiceServer(s grpc.ServiceRegistrar, srv WorkerServiceServer) {
	// If the following call pancis, it indicates UnimplementedWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerService_ServiceDesc, srv)
}

func _WorkerService_OpenSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).OpenSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_OpenSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).OpenSession(ctx, req.(*OpenSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerServiceServer).Session(&grpc.GenericServerStream[ClientSessionMessage, NodeSessionEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_SessionServer = grpc.BidiStreamingServer[ClientSessionMessage, NodeSessionEvent]

func _WorkerService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_AllocateStaging_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateStagingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).AllocateStaging(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_AllocateStaging_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).AllocateStaging(ctx, req.(*AllocateStagingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_AcquireRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).AcquireRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_AcquireRegion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).AcquireRegion(ctx, req.(*AcquireRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_DeleteStaging_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStagingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).DeleteStaging(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_DeleteStaging_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).DeleteStaging(ctx, req.(*DeleteStagingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_SetInline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetInlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).SetInline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_SetInline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).SetInline(ctx, req.(*SetInlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Stat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Stat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Scan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Scan(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_MSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).MSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_MSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).MSet(ctx, req.(*MSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_MGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).MGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_MGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).MGet(ctx, req.(*MGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_SetRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).SetRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_SetRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).SetRange(ctx, req.(*SetRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_HSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).HSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_HSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).HSet(ctx, req.(*HSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_HGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).HGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_HGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).HGet(ctx, req.(*HGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_HMGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HMGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).HMGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_HMGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).HMGet(ctx, req.(*HMGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_HGetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HGetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).HGetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_HGetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).HGetAll(ctx, req.(*HGetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_HDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).HDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_HDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).HDelete(ctx, req.(*HDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_HScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).HScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_HScan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).HScan(ctx, req.(*HScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_HWriteAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HWriteAtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).HWriteAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_HWriteAt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).HWriteAt(ctx, req.(*HWriteAtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerService_ServiceDesc is the grpc.ServiceDesc for WorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dms.v1.WorkerService",
	HandlerType: (*WorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenSession",
			Handler:    _WorkerService_OpenSession_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _WorkerService_Heartbeat_Handler,
		},
		{
			MethodName: "AllocateStaging",
			Handler:    _WorkerService_AllocateStaging_Handler,
		},
		{
			MethodName: "AcquireRegion",
			Handler:    _WorkerService_AcquireRegion_Handler,
		},
		{
			MethodName: "DeleteStaging",
			Handler:    _WorkerService_DeleteStaging_Handler,
		},
		{
			MethodName: "SetInline",
			Handler:    _WorkerService_SetInline_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _WorkerService_Set_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _WorkerService_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _WorkerService_Get_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _WorkerService_Stat_Handler,
		},
		{
			MethodName: "Scan",
			Handler:    _WorkerService_Scan_Handler,
		},
		{
			MethodName: "MSet",
			Handler:    _WorkerService_MSet_Handler,
		},
		{
			MethodName: "MGet",
			Handler:    _WorkerService_MGet_Handler,
		},
		{
			MethodName: "SetRange",
			Handler:    _WorkerService_SetRange_Handler,
		},
		{
			MethodName: "HSet",
			Handler:    _WorkerService_HSet_Handler,
		},
		{
			MethodName: "HGet",
			Handler:    _WorkerService_HGet_Handler,
		},
		{
			MethodName: "HMGet",
			Handler:    _WorkerService_HMGet_Handler,
		},
		{
			MethodName: "HGetAll",
			Handler:    _WorkerService_HGetAll_Handler,
		},
		{
			MethodName: "HDelete",
			Handler:    _WorkerService_HDelete_Handler,
		},
		{
			MethodName: "HScan",
			Handler:    _WorkerService_HScan_Handler,
		},
		{
			MethodName: "HWriteAt",
			Handler:    _WorkerService_HWriteAt_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _WorkerService_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "dms/v1/client_node.proto",
}

const (
	WorkerPayloadService_Upload_FullMethodName   = "/dms.v1.WorkerPayloadService/Upload"
	WorkerPayloadService_Download_FullMethodName = "/dms.v1.WorkerPayloadService/Download"
)

// WorkerPayloadServiceClient is the client API for WorkerPayloadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC fallback for bounded payload bytes. Shared-memory Endpoint providers do
// not call these methods; they map the arena once through an internal FD broker
// and return a receipt for the same physical pages.
type WorkerPayloadServiceClient interface {
	Upload(ctx context.Context, in *UploadPayloadRequest, opts ...grpc.CallOption) (*UploadPayloadResponse, error)
	Download(ctx context.Context, in *DownloadPayloadRequest, opts ...grpc.CallOption) (*DownloadPayloadResponse, error)
}

type workerPayloadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerPayloadServiceClient(cc grpc.ClientConnInterface) WorkerPayloadServiceClient {
	return &workerPayloadServiceClient{cc}
}

func (c *workerPayloadServiceClient) Upload(ctx context.Context, in *UploadPayloadRequest, opts ...grpc.CallOption) (*UploadPayloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadPayloadResponse)
	err := c.cc.Invoke(ctx, WorkerPayloadService_Upload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerPayloadServiceClient) Download(ctx context.Context, in *DownloadPayloadRequest, opts ...grpc.CallOption) (*DownloadPayloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadPayloadResponse)
	err := c.cc.Invoke(ctx, WorkerPayloadService_Download_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerPayloadServiceServer is the server API for WorkerPayloadService service.
// All implementations must embed UnimplementedWorkerPayloadServiceServer
// for forward compatibility.
//
// gRPC fallback for bounded payload bytes. Shared-memory Endpoint providers do
// not call these methods; they map the arena once through an internal FD broker
// and return a receipt for the same physical pages.
type WorkerPayloadServiceServer interface {
	Upload(context.Context, *UploadPayloadRequest) (*UploadPayloadResponse, error)
	Download(context.Context, *DownloadPayloadRequest) (*DownloadPayloadResponse, error)
	mustEmbedUnimplementedWorkerPayloadServiceServer()
}

// UnimplementedWorkerPayloadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerPayloadServiceServer struct{}

func (UnimplementedWorkerPayloadServiceServer) Upload(context.Context, *UploadPayloadRequest) (*UploadPayloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedWorkerPayloadServiceServer) Download(context.Context, *DownloadPayloadRequest) (*DownloadPayloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedWorkerPayloadServiceServer) mustEmbedUnimplementedWorkerPayloadServiceServer() {}
func (UnimplementedWorkerPayloadServiceServer) testEmbeddedByValue()                              {}

// UnsafeWorkerPayloadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerPayloadServiceServer will
// result in compilation errors.
type UnsafeWorkerPayloadServiceServer interface {
	mustEmbedUnimplementedWorkerPayloadServiceServer()
}

func RegisterWorkerPayloadServiceServer(s grpc.ServiceRegistrar, srv WorkerPayloadServiceServer) {
	// If the following call pancis, it indicates UnimplementedWorkerPayloadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerPayloadService_ServiceDesc, srv)
}

func _WorkerPayloadService_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadPayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerPayloadServiceServer).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerPayloadService_Upload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerPayloadServiceServer).Upload(ctx, req.(*UploadPayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerPayloadService_Download_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadPayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerPayloadServiceServer).Download(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerPayloadService_Download_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerPayloadServiceServer).Download(ctx, req.(*DownloadPayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerPayloadService_ServiceDesc is the grpc.ServiceDesc for WorkerPayloadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerPayloadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dms.v1.WorkerPayloadService",
	HandlerType: (*WorkerPayloadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upload",
			Handler:    _WorkerPayloadService_Upload_Handler,
		},
		{
			MethodName: "Download",
			Handler:    _WorkerPayloadService_Download_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dms/v1/client_node.proto",
}
