// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: dms/v1/types.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorKind int32

const (
	ErrorKind_ERROR_KIND_UNKNOWN             ErrorKind = 0
	ErrorKind_ERROR_KIND_INVALID_ARGUMENT    ErrorKind = 1
	ErrorKind_ERROR_KIND_NOT_FOUND           ErrorKind = 2
	ErrorKind_ERROR_KIND_ALREADY_EXISTS      ErrorKind = 3
	ErrorKind_ERROR_KIND_PERMISSION_DENIED   ErrorKind = 4
	ErrorKind_ERROR_KIND_RESOURCE_EXHAUSTED  ErrorKind = 5
	ErrorKind_ERROR_KIND_FAILED_PRECONDITION ErrorKind = 6
	ErrorKind_ERROR_KIND_ABORTED             ErrorKind = 7
	ErrorKind_ERROR_KIND_UNIMPLEMENTED       ErrorKind = 8
	ErrorKind_ERROR_KIND_INTERNAL            ErrorKind = 9
	ErrorKind_ERROR_KIND_UNAVAILABLE         ErrorKind = 10
	ErrorKind_ERROR_KIND_DATA_LOSS           ErrorKind = 11
	ErrorKind_ERROR_KIND_UNAUTHENTICATED     ErrorKind = 12
	ErrorKind_ERROR_KIND_DEADLINE_EXCEEDED   ErrorKind = 13
)

// Enum value maps for ErrorKind.
var (
	ErrorKind_name = map[int32]string{
		0:  "ERROR_KIND_UNKNOWN",
		1:  "ERROR_KIND_INVALID_ARGUMENT",
		2:  "ERROR_KIND_NOT_FOUND",
		3:  "ERROR_KIND_ALREADY_EXISTS",
		4:  "ERROR_KIND_PERMISSION_DENIED",
		5:  "ERROR_KIND_RESOURCE_EXHAUSTED",
		6:  "ERROR_KIND_FAILED_PRECONDITION",
		7:  "ERROR_KIND_ABORTED",
		8:  "ERROR_KIND_UNIMPLEMENTED",
		9:  "ERROR_KIND_INTERNAL",
		10: "ERROR_KIND_UNAVAILABLE",
		11: "ERROR_KIND_DATA_LOSS",
		12: "ERROR_KIND_UNAUTHENTICATED",
		13: "ERROR_KIND_DEADLINE_EXCEEDED",
	}
	ErrorKind_value = map[string]int32{
		"ERROR_KIND_UNKNOWN":             0,
		"ERROR_KIND_INVALID_ARGUMENT":    1,
		"ERROR_KIND_NOT_FOUND":           2,
		"ERROR_KIND_ALREADY_EXISTS":      3,
		"ERROR_KIND_PERMISSION_DENIED":   4,
		"ERROR_KIND_RESOURCE_EXHAUSTED":  5,
		"ERROR_KIND_FAILED_PRECONDITION": 6,
		"ERROR_KIND_ABORTED":             7,
		"ERROR_KIND_UNIMPLEMENTED":       8,
		"ERROR_KIND_INTERNAL":            9,
		"ERROR_KIND_UNAVAILABLE":         10,
		"ERROR_KIND_DATA_LOSS":           11,
		"ERROR_KIND_UNAUTHENTICATED":     12,
		"ERROR_KIND_DEADLINE_EXCEEDED":   13,
	}
)

func (x ErrorKind) Enum() *ErrorKind {
	p := new(ErrorKind)
	*p = x
	return p
}

func (x ErrorKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorKind) Descriptor() protoreflect.EnumDescriptor {
	return file_dms_v1_types_proto_enumTypes[0].Descriptor()
}

func (ErrorKind) Type() protoreflect.EnumType {
	return &file_dms_v1_types_proto_enumTypes[0]
}

func (x ErrorKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorKind.Descriptor instead.
func (ErrorKind) EnumDescriptor() ([]byte, []int) {
	return file_dms_v1_types_proto_rawDescGZIP(), []int{0}
}

type Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_dms_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_dms_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_dms_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *Key) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type HashField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashField) Reset() {
	*x = HashField{}
	mi := &file_dms_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashField) ProtoMessage() {}

func (x *HashField) ProtoReflect() protoreflect.Message {
	mi := &file_dms_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashField.ProtoReflect.Descriptor instead.
func (*HashField) Descriptor() ([]byte, []int) {
	return file_dms_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *HashField) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// One logical mutation identity, stable across transport retries.
//
// The UUID identifies one SDK process incarnation. The sequence is only
// incremented for a new logical operation; retries reuse the same pair.
type OperationId struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ClientInstanceId []byte                 `protobuf:"bytes,1,opt,name=client_instance_id,json=clientInstanceId,proto3" json:"client_instance_id,omitempty"`
	Sequence         uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OperationId) Reset() {
	*x = OperationId{}
	mi := &file_dms_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationId) ProtoMessage() {}

func (x *OperationId) ProtoReflect() protoreflect.Message {
	mi := &file_dms_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationId.ProtoReflect.Descriptor instead.
func (*OperationId) Descriptor() ([]byte, []int) {
	return file_dms_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *OperationId) GetClientInstanceId() []byte {
	if x != nil {
		return x.ClientInstanceId
	}
	return nil
}

func (x *OperationId) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type ByteRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        uint64                 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ByteRange) Reset() {
	*x = ByteRange{}
	mi := &file_dms_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ByteRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByteRange) ProtoMessage() {}

func (x *ByteRange) ProtoReflect() protoreflect.Message {
	mi := &file_dms_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByteRange.ProtoReflect.Descriptor instead.
func (*ByteRange) Descriptor() ([]byte, []int) {
	return file_dms_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *ByteRange) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ByteRange) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type ObjectInfo struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Key                    *Key                   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Length                 uint64                 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	ModifiedTimeUnixMillis int64                  `protobuf:"varint,3,opt,name=modified_time_unix_millis,json=modifiedTimeUnixMillis,proto3" json:"modified_time_unix_millis,omitempty"`
	Version                uint64                 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ObjectInfo) Reset() {
	*x = ObjectInfo{}
	mi := &file_dms_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectInfo) ProtoMessage() {}

func (x *ObjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dms_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectInfo.ProtoReflect.Descriptor instead.
func (*ObjectInfo) Descriptor() ([]byte, []int) {
	return file_dms_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *ObjectInfo) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ObjectInfo) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *ObjectInfo) GetModifiedTimeUnixMillis() int64 {
	if x != nil {
		return x.ModifiedTimeUnixMillis
	}
	return 0
}

func (x *ObjectInfo) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ObjectScanOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	StartAfter    []byte                 `protobuf:"bytes,2,opt,name=start_after,json=startAfter,proto3,oneof" json:"start_after,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectScanOptions) Reset() {
	*x = ObjectScanOptions{}
	mi := &file_dms_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectScanOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectScanOptions) ProtoMessage() {}

func (x *ObjectScanOptions) ProtoReflect() protoreflect.Message {
	mi := &file_dms_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectScanOptions.ProtoReflect.Descriptor instead.
func (*ObjectScanOptions) Descriptor() ([]byte, []int) {
	return file_dms_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *ObjectScanOptions) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ObjectScanOptions) GetStartAfter() []byte {
	if x != nil {
		return x.StartAfter
	}
	return nil
}

func (x *ObjectScanOptions) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

// Wire-only DTO for carrying a native DmsError across process boundaries.
// SDK and server code must convert at the edge instead of exposing this type as
// a public language API.
type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DmsCode       uint32                 `protobuf:"varint,1,opt,name=dms_code,json=dmsCode,proto3" json:"dms_code,omitempty"`
	Kind          ErrorKind              `protobuf:"varint,2,opt,name=kind,proto3,enum=dms.v1.ErrorKind" json:"kind,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_dms_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_dms_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_dms_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *ErrorDetail) GetDmsCode() uint32 {
	if x != nil {
		return x.DmsCode
	}
	return 0
}

func (x *ErrorDetail) GetKind() ErrorKind {
	if x != nil {
		return x.Kind
	}
	return ErrorKind_ERROR_KIND_UNKNOWN
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ShmDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Region is the memfd/mmap identity visible to the Client. A jemalloc arena,
	// if introduced inside dms-node later, remains an allocator implementation
	// detail and never appears on the wire.
	RegionId     uint64 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Offset       uint64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Length       uint64 `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	AllocationId uint64 `protobuf:"varint,5,opt,name=allocation_id,json=allocationId,proto3" json:"allocation_id,omitempty"`
	// A write staging slice does not own a read view. Read targets set this
	// field so the SDK can report the released-through watermark on Drop.
	ViewEpoch  *uint64 `protobuf:"varint,6,opt,name=view_epoch,json=viewEpoch,proto3,oneof" json:"view_epoch,omitempty"`
	TransferId []byte  `protobuf:"bytes,10,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	// Opaque per-allocation write-return token. SDK must echo it only after the
	// writable SHM borrow is no longer reachable; stale tokens never authorize a
	// different allocation because Node validates allocation_id and generation.
	ReleaseToken  []byte `protobuf:"bytes,11,opt,name=release_token,json=releaseToken,proto3" json:"release_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShmDescriptor) Reset() {
	*x = ShmDescriptor{}
	mi := &file_dms_v1_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShmDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShmDescriptor) ProtoMessage() {}

func (x *ShmDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_dms_v1_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShmDescriptor.ProtoReflect.Descriptor instead.
func (*ShmDescriptor) Descriptor() ([]byte, []int) {
	return file_dms_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *ShmDescriptor) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *ShmDescriptor) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ShmDescriptor) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *ShmDescriptor) GetAllocationId() uint64 {
	if x != nil {
		return x.AllocationId
	}
	return 0
}

func (x *ShmDescriptor) GetViewEpoch() uint64 {
	if x != nil && x.ViewEpoch != nil {
		return *x.ViewEpoch
	}
	return 0
}

func (x *ShmDescriptor) GetTransferId() []byte {
	if x != nil {
		return x.TransferId
	}
	return nil
}

func (x *ShmDescriptor) GetReleaseToken() []byte {
	if x != nil {
		return x.ReleaseToken
	}
	return nil
}

// A destination prepared by dms-node for one bounded payload transfer.
//
// This is an internal Endpoint descriptor, not a transport choice exposed to
// KV operation code. A local provider writes the shared mapping directly; the
// universal fallback calls WorkerPayloadService; future peer providers may use
// the opaque RDMA/UB descriptors.
type PayloadTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Target:
	//
	//	*PayloadTarget_Shm
	//	*PayloadTarget_Grpc
	//	*PayloadTarget_Rdma
	//	*PayloadTarget_Ub
	Target        isPayloadTarget_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadTarget) Reset() {
	*x = PayloadTarget{}
	mi := &file_dms_v1_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadTarget) ProtoMessage() {}

func (x *PayloadTarget) ProtoReflect() protoreflect.Message {
	mi := &file_dms_v1_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadTarget.ProtoReflect.Descriptor instead.
func (*PayloadTarget) Descriptor() ([]byte, []int) {
	return file_dms_v1_types_proto_rawDescGZIP(), []int{8}
}

func (x *PayloadTarget) GetTarget() isPayloadTarget_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *PayloadTarget) GetShm() *ShmDescriptor {
	if x != nil {
		if x, ok := x.Target.(*PayloadTarget_Shm); ok {
			return x.Shm
		}
	}
	return nil
}

func (x *PayloadTarget) GetGrpc() *GrpcTarget {
	if x != nil {
		if x, ok := x.Target.(*PayloadTarget_Grpc); ok {
			return x.Grpc
		}
	}
	return nil
}

func (x *PayloadTarget) GetRdma() *RdmaTarget {
	if x != nil {
		if x, ok := x.Target.(*PayloadTarget_Rdma); ok {
			return x.Rdma
		}
	}
	return nil
}

func (x *PayloadTarget) GetUb() *UbTarget {
	if x != nil {
		if x, ok := x.Target.(*PayloadTarget_Ub); ok {
			return x.Ub
		}
	}
	return nil
}

type isPayloadTarget_Target interface {
	isPayloadTarget_Target()
}

type PayloadTarget_Shm struct {
	Shm *ShmDescriptor `protobuf:"bytes,1,opt,name=shm,proto3,oneof"`
}

type PayloadTarget_Grpc struct {
	Grpc *GrpcTarget `protobuf:"bytes,2,opt,name=grpc,proto3,oneof"`
}

type PayloadTarget_Rdma struct {
	Rdma *RdmaTarget `protobuf:"bytes,3,opt,name=rdma,proto3,oneof"`
}

type PayloadTarget_Ub struct {
	Ub *UbTarget `protobuf:"bytes,4,opt,name=ub,proto3,oneof"`
}

func (*PayloadTarget_Shm) isPayloadTarget_Target() {}

func (*PayloadTarget_Grpc) isPayloadTarget_Target() {}

func (*PayloadTarget_Rdma) isPayloadTarget_Target() {}

func (*PayloadTarget_Ub) isPayloadTarget_Target() {}

type GrpcTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    []byte                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Length        uint64                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcTarget) Reset() {
	*x = GrpcTarget{}
	mi := &file_dms_v1_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcTarget) ProtoMessage() {}

func (x *GrpcTarget) ProtoReflect() protoreflect.Message {
	mi := &file_dms_v1_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcTarget.ProtoReflect.Descriptor instead.
func (*GrpcTarget) Descriptor() ([]byte, []int) {
	return file_dms_v1_types_proto_rawDescGZIP(), []int{9}
}

func (x *GrpcTarget) GetTransferId() []byte {
	if x != nil {
		return x.TransferId
	}
	return nil
}

func (x *GrpcTarget) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *GrpcTarget) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

// RDMA and UB descriptors are intentionally opaque at the common protocol
// boundary. Their provider-specific registration fields evolve behind the
// data-channel implementation without leaking into WorkerService semantics.
type RdmaTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Descriptor_   []byte                 `protobuf:"bytes,1,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	TransferId    []byte                 `protobuf:"bytes,2,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Length        uint64                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RdmaTarget) Reset() {
	*x = RdmaTarget{}
	mi := &file_dms_v1_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RdmaTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RdmaTarget) ProtoMessage() {}

func (x *RdmaTarget) ProtoReflect() protoreflect.Message {
	mi := &file_dms_v1_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RdmaTarget.ProtoReflect.Descriptor instead.
func (*RdmaTarget) Descriptor() ([]byte, []int) {
	return file_dms_v1_types_proto_rawDescGZIP(), []int{10}
}

func (x *RdmaTarget) GetDescriptor_() []byte {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

func (x *RdmaTarget) GetTransferId() []byte {
	if x != nil {
		return x.TransferId
	}
	return nil
}

func (x *RdmaTarget) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type UbTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Descriptor_   []byte                 `protobuf:"bytes,1,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	TransferId    []byte                 `protobuf:"bytes,2,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Length        uint64                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UbTarget) Reset() {
	*x = UbTarget{}
	mi := &file_dms_v1_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UbTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UbTarget) ProtoMessage() {}

func (x *UbTarget) ProtoReflect() protoreflect.Message {
	mi := &file_dms_v1_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UbTarget.ProtoReflect.Descriptor instead.
func (*UbTarget) Descriptor() ([]byte, []int) {
	return file_dms_v1_types_proto_rawDescGZIP(), []int{11}
}

func (x *UbTarget) GetDescriptor_() []byte {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

func (x *UbTarget) GetTransferId() []byte {
	if x != nil {
		return x.TransferId
	}
	return nil
}

func (x *UbTarget) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

// Proof that the data channel finished writing one previously issued target.
// For SHM this identifies the staged mapping that the client has finished
// writing; for remote providers it identifies a completed transfer ticket.
type TransferReceipt struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TransferId         []byte                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Length             uint64                 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Digest             []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	TargetAllocationId uint64                 `protobuf:"varint,4,opt,name=target_allocation_id,json=targetAllocationId,proto3" json:"target_allocation_id,omitempty"`
	ReleaseToken       []byte                 `protobuf:"bytes,5,opt,name=release_token,json=releaseToken,proto3" json:"release_token,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TransferReceipt) Reset() {
	*x = TransferReceipt{}
	mi := &file_dms_v1_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferReceipt) ProtoMessage() {}

func (x *TransferReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_dms_v1_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferReceipt.ProtoReflect.Descriptor instead.
func (*TransferReceipt) Descriptor() ([]byte, []int) {
	return file_dms_v1_types_proto_rawDescGZIP(), []int{12}
}

func (x *TransferReceipt) GetTransferId() []byte {
	if x != nil {
		return x.TransferId
	}
	return nil
}

func (x *TransferReceipt) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *TransferReceipt) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *TransferReceipt) GetTargetAllocationId() uint64 {
	if x != nil {
		return x.TargetAllocationId
	}
	return 0
}

func (x *TransferReceipt) GetReleaseToken() []byte {
	if x != nil {
		return x.ReleaseToken
	}
	return nil
}

type ReleasedWriteAllocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllocationId  uint64                 `protobuf:"varint,1,opt,name=allocation_id,json=allocationId,proto3" json:"allocation_id,omitempty"`
	ReleaseToken  []byte                 `protobuf:"bytes,2,opt,name=release_token,json=releaseToken,proto3" json:"release_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleasedWriteAllocation) Reset() {
	*x = ReleasedWriteAllocation{}
	mi := &file_dms_v1_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleasedWriteAllocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleasedWriteAllocation) ProtoMessage() {}

func (x *ReleasedWriteAllocation) ProtoReflect() protoreflect.Message {
	mi := &file_dms_v1_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleasedWriteAllocation.ProtoReflect.Descriptor instead.
func (*ReleasedWriteAllocation) Descriptor() ([]byte, []int) {
	return file_dms_v1_types_proto_rawDescGZIP(), []int{13}
}

func (x *ReleasedWriteAllocation) GetAllocationId() uint64 {
	if x != nil {
		return x.AllocationId
	}
	return 0
}

func (x *ReleasedWriteAllocation) GetReleaseToken() []byte {
	if x != nil {
		return x.ReleaseToken
	}
	return nil
}

type StagedValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StagingId     uint64                 `protobuf:"varint,1,opt,name=staging_id,json=stagingId,proto3" json:"staging_id,omitempty"`
	Receipt       *TransferReceipt       `protobuf:"bytes,2,opt,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StagedValue) Reset() {
	*x = StagedValue{}
	mi := &file_dms_v1_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StagedValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StagedValue) ProtoMessage() {}

func (x *StagedValue) ProtoReflect() protoreflect.Message {
	mi := &file_dms_v1_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StagedValue.ProtoReflect.Descriptor instead.
func (*StagedValue) Descriptor() ([]byte, []int) {
	return file_dms_v1_types_proto_rawDescGZIP(), []int{14}
}

func (x *StagedValue) GetStagingId() uint64 {
	if x != nil {
		return x.StagingId
	}
	return 0
}

func (x *StagedValue) GetReceipt() *TransferReceipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

var File_dms_v1_types_proto protoreflect.FileDescriptor

const file_dms_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x12dms/v1/types.proto\x12\x06dms.v1\"\x1b\n" +
	"\x03Key\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"!\n" +
	"\tHashField\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"W\n" +
	"\vOperationId\x12,\n" +
	"\x12client_instance_id\x18\x01 \x01(\fR\x10clientInstanceId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\";\n" +
	"\tByteRange\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x04R\x06length\"\x98\x01\n" +
	"\n" +
	"ObjectInfo\x12\x1d\n" +
	"\x03key\x18\x01 \x01(\v2\v.dms.v1.KeyR\x03key\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x04R\x06length\x129\n" +
	"\x19modified_time_unix_millis\x18\x03 \x01(\x03R\x16modifiedTimeUnixMillis\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x04R\aversion\"w\n" +
	"\x11ObjectScanOptions\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12$\n" +
	"\vstart_after\x18\x02 \x01(\fH\x00R\n" +
	"startAfter\x88\x01\x01\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursorB\x0e\n" +
	"\f_start_after\"i\n" +
	"\vErrorDetail\x12\x19\n" +
	"\bdms_code\x18\x01 \x01(\rR\admsCode\x12%\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x11.dms.v1.ErrorKindR\x04kind\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xcd\x02\n" +
	"\rShmDescriptor\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x04 \x01(\x04R\x06length\x12#\n" +
	"\rallocation_id\x18\x05 \x01(\x04R\fallocationId\x12\"\n" +
	"\n" +
	"view_epoch\x18\x06 \x01(\x04H\x00R\tviewEpoch\x88\x01\x01\x12\x1f\n" +
	"\vtransfer_id\x18\n" +
	" \x01(\fR\n" +
	"transferId\x12#\n" +
	"\rrelease_token\x18\v \x01(\fR\freleaseTokenB\r\n" +
	"\v_view_epochJ\x04\b\x02\x10\x03J\x04\b\a\x10\bJ\x04\b\b\x10\tJ\x04\b\t\x10\n" +
	"R\x11region_generationR\x0efd_broker_pathR\bfd_tokenR\farena_length\"\xbc\x01\n" +
	"\rPayloadTarget\x12)\n" +
	"\x03shm\x18\x01 \x01(\v2\x15.dms.v1.ShmDescriptorH\x00R\x03shm\x12(\n" +
	"\x04grpc\x18\x02 \x01(\v2\x12.dms.v1.GrpcTargetH\x00R\x04grpc\x12(\n" +
	"\x04rdma\x18\x03 \x01(\v2\x12.dms.v1.RdmaTargetH\x00R\x04rdma\x12\"\n" +
	"\x02ub\x18\x04 \x01(\v2\x10.dms.v1.UbTargetH\x00R\x02ubB\b\n" +
	"\x06target\"[\n" +
	"\n" +
	"GrpcTarget\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\fR\n" +
	"transferId\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x04R\x06length\"e\n" +
	"\n" +
	"RdmaTarget\x12\x1e\n" +
	"\n" +
	"descriptor\x18\x01 \x01(\fR\n" +
	"descriptor\x12\x1f\n" +
	"\vtransfer_id\x18\x02 \x01(\fR\n" +
	"transferId\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x04R\x06length\"c\n" +
	"\bUbTarget\x12\x1e\n" +
	"\n" +
	"descriptor\x18\x01 \x01(\fR\n" +
	"descriptor\x12\x1f\n" +
	"\vtransfer_id\x18\x02 \x01(\fR\n" +
	"transferId\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x04R\x06length\"\xb9\x01\n" +
	"\x0fTransferReceipt\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\fR\n" +
	"transferId\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x04R\x06length\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\x120\n" +
	"\x14target_allocation_id\x18\x04 \x01(\x04R\x12targetAllocationId\x12#\n" +
	"\rrelease_token\x18\x05 \x01(\fR\freleaseToken\"c\n" +
	"\x17ReleasedWriteAllocation\x12#\n" +
	"\rallocation_id\x18\x01 \x01(\x04R\fallocationId\x12#\n" +
	"\rrelease_token\x18\x02 \x01(\fR\freleaseToken\"_\n" +
	"\vStagedValue\x12\x1d\n" +
	"\n" +
	"staging_id\x18\x01 \x01(\x04R\tstagingId\x121\n" +
	"\areceipt\x18\x02 \x01(\v2\x17.dms.v1.TransferReceiptR\areceipt*\xad\x03\n" +
	"\tErrorKind\x12\x16\n" +
	"\x12ERROR_KIND_UNKNOWN\x10\x00\x12\x1f\n" +
	"\x1bERROR_KIND_INVALID_ARGUMENT\x10\x01\x12\x18\n" +
	"\x14ERROR_KIND_NOT_FOUND\x10\x02\x12\x1d\n" +
	"\x19ERROR_KIND_ALREADY_EXISTS\x10\x03\x12 \n" +
	"\x1cERROR_KIND_PERMISSION_DENIED\x10\x04\x12!\n" +
	"\x1dERROR_KIND_RESOURCE_EXHAUSTED\x10\x05\x12\"\n" +
	"\x1eERROR_KIND_FAILED_PRECONDITION\x10\x06\x12\x16\n" +
	"\x12ERROR_KIND_ABORTED\x10\a\x12\x1c\n" +
	"\x18ERROR_KIND_UNIMPLEMENTED\x10\b\x12\x17\n" +
	"\x13ERROR_KIND_INTERNAL\x10\t\x12\x1a\n" +
	"\x16ERROR_KIND_UNAVAILABLE\x10\n" +
	"\x12\x18\n" +
	"\x14ERROR_KIND_DATA_LOSS\x10\v\x12\x1e\n" +
	"\x1aERROR_KIND_UNAUTHENTICATED\x10\f\x12 \n" +
	"\x1cERROR_KIND_DEADLINE_EXCEEDED\x10\rb\x06proto3"

var (
	file_dms_v1_types_proto_rawDescOnce sync.Once
	file_dms_v1_types_proto_rawDescData []byte
)

func file_dms_v1_types_proto_rawDescGZIP() []byte {
	file_dms_v1_types_proto_rawDescOnce.Do(func() {
		file_dms_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dms_v1_types_proto_rawDesc), len(file_dms_v1_types_proto_rawDesc)))
	})
	return file_dms_v1_types_proto_rawDescData
}

var file_dms_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dms_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_dms_v1_types_proto_goTypes = []any{
	(ErrorKind)(0),                  // 0: dms.v1.ErrorKind
	(*Key)(nil),                     // 1: dms.v1.Key
	(*HashField)(nil),               // 2: dms.v1.HashField
	(*OperationId)(nil),             // 3: dms.v1.OperationId
	(*ByteRange)(nil),               // 4: dms.v1.ByteRange
	(*ObjectInfo)(nil),              // 5: dms.v1.ObjectInfo
	(*ObjectScanOptions)(nil),       // 6: dms.v1.ObjectScanOptions
	(*ErrorDetail)(nil),             // 7: dms.v1.ErrorDetail
	(*ShmDescriptor)(nil),           // 8: dms.v1.ShmDescriptor
	(*PayloadTarget)(nil),           // 9: dms.v1.PayloadTarget
	(*GrpcTarget)(nil),              // 10: dms.v1.GrpcTarget
	(*RdmaTarget)(nil),              // 11: dms.v1.RdmaTarget
	(*UbTarget)(nil),                // 12: dms.v1.UbTarget
	(*TransferReceipt)(nil),         // 13: dms.v1.TransferReceipt
	(*ReleasedWriteAllocation)(nil), // 14: dms.v1.ReleasedWriteAllocation
	(*StagedValue)(nil),             // 15: dms.v1.StagedValue
}
var file_dms_v1_types_proto_depIdxs = []int32{
	1,  // 0: dms.v1.ObjectInfo.key:type_name -> dms.v1.Key
	0,  // 1: dms.v1.ErrorDetail.kind:type_name -> dms.v1.ErrorKind
	8,  // 2: dms.v1.PayloadTarget.shm:type_name -> dms.v1.ShmDescriptor
	10, // 3: dms.v1.PayloadTarget.grpc:type_name -> dms.v1.GrpcTarget
	11, // 4: dms.v1.PayloadTarget.rdma:type_name -> dms.v1.RdmaTarget
	12, // 5: dms.v1.PayloadTarget.ub:type_name -> dms.v1.UbTarget
	13, // 6: dms.v1.StagedValue.receipt:type_name -> dms.v1.TransferReceipt
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_dms_v1_types_proto_init() }
func file_dms_v1_types_proto_init() {
	if File_dms_v1_types_proto != nil {
		return
	}
	file_dms_v1_types_proto_msgTypes[5].OneofWrappers = []any{}
	file_dms_v1_types_proto_msgTypes[7].OneofWrappers = []any{}
	file_dms_v1_types_proto_msgTypes[8].OneofWrappers = []any{
		(*PayloadTarget_Shm)(nil),
		(*PayloadTarget_Grpc)(nil),
		(*PayloadTarget_Rdma)(nil),
		(*PayloadTarget_Ub)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dms_v1_types_proto_rawDesc), len(file_dms_v1_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dms_v1_types_proto_goTypes,
		DependencyIndexes: file_dms_v1_types_proto_depIdxs,
		EnumInfos:         file_dms_v1_types_proto_enumTypes,
		MessageInfos:      file_dms_v1_types_proto_msgTypes,
	}.Build()
	File_dms_v1_types_proto = out.File
	file_dms_v1_types_proto_goTypes = nil
	file_dms_v1_types_proto_depIdxs = nil
}
