cluster_id = 'afs_3fs_delete_v84_20261007_r1'

[ib_devices]
default_pkey_index = 0

[fdb]
clusterFile = '/mnt/lima-afscdata/afs-delivery/threefs-delete-v84-20261007-r1/data/foundationdb/fdb.cluster'

[mgmtd_client]
mgmtd_server_addresses = [ 'RDMA://192.168.109.11:24101' ]

[user_info]
uid = 0
gid = 0
token = 'AADHHSOs8QA92iRe2wB1fmuL'
