attr_timeout = 2
entry_timeout = 2
fsync_length_hint = false
fdatasync_update_length = true
enable_read_cache = true

[[common.log.categories]]
categories = [ '.' ]
handlers = [ 'normal' ]

[[common.log.handlers]]
async = true
name = 'normal'
start_level = 'NONE'
writer_type = 'FILE'
file_path = '/mnt/lima-afscdata/afs-delivery/threefs-delete-v84-20261007-r1/log/fuse.log'

[mgmtd]
mgmtd_server_addresses = [ 'RDMA://192.168.109.11:24101' ]

[periodic_sync]
enable = true
interval = '500ms'
limit = 16

[io_bufs]
max_buf_size = '1MB'
