cluster_id = 'afs_3fs_delete_v84_20261007_r1'

[ib_devices]
default_pkey_index = 0

[kv_engine.fdb]
clusterFile = '/mnt/lima-afscdata/afs-delivery/threefs-delete-v84-20261007-r1/data/foundationdb/fdb.cluster'
