[[common.log.categories]]
categories = [ '.' ]
handlers = [ 'normal' ]

[[common.log.handlers]]
async = true
name = 'normal'
start_level = 'NONE'
writer_type = 'FILE'
file_path = '/mnt/lima-afsadata/afs-delivery/threefs-delete-v84-20261007-r1/log/mgmtd.log'

[[server.base.groups]]
[server.base.groups.listener]
listen_port = 24101

[[server.base.groups]]
[server.base.groups.listener]
listen_port = 0

[server.service]
allow_heartbeat_from_unregistered = true
