[[common.log.categories]]
categories = [ '.' ]
handlers = [ 'normal' ]

[[common.log.handlers]]
async = true
name = 'normal'
start_level = 'NONE'
writer_type = 'FILE'
file_path = '/mnt/lima-afsadata/afs-delivery/threefs-delete-v84-20261007-r1/log/storage.log'

[[server.base.groups]]
[server.base.groups.listener]
listen_port = 24103

[[server.base.groups]]
[server.base.groups.listener]
listen_port = 0

[server.allocate_worker]
min_remain_groups = 0
max_remain_groups = 1
max_reserved_chunks = '1GB'

[server.mgmtd]
mgmtd_server_addresses = [ 'RDMA://192.168.109.11:24101' ]

[server.targets]
target_paths = [ '/mnt/lima-afsadata/afs-delivery/threefs-delete-v84-20261007-r1/data/storage/data1' ]
allow_disk_without_uuid = true

[server.aio_read_worker]
enable_io_uring = false

[server.buffer_pool]
big_rdmabuf_count = 16
big_rdmabuf_size = '16MB'
rdmabuf_count = 32
rdmabuf_size = '4MB'
